"Flange_Dia"= 179.65
"Regen_Thickness"= 1.5
"Regen_To_Inner"=2
"Faceplate_Area"=95.65
"Regen_Rib_Thickness"=1
"Flange_Thickness"= 10
"Faceplate_To_Chamber_Extrusion"=5
"Injector_MCCN_O-Ring"=3
"Ox_Orifice" = 1.829247371
"Fuel_Orifice"= 1.65242067
"OxFuel_Dist_Downstream"= 3
"Fuel_Dist_From_Center"=29.2826
"OxFuel_HalfAngle"=30
"D1@Sketch1"="Flange_Dia"
"D2@Sketch1"="Faceplate_Area"
"D1@Boss-Extrude1"="Flange_Thickness"
"D1@Sketch3"="Faceplate_Area"
"D1@tbh idk" = "Flange_Thickness" / 2
"D1@Sketch4"="Faceplate_Area"
"D1@Extrusion to Fuel Man" = "Flange_Thickness" / 2
"D1@Ox Profile" = "Fuel_Orifice"
"D2@Ox Profile" = "Fuel_Dist_From_Center"
"D3@Ox Profile" = "Ox_Orifice"
"D1@Flange" = "Flange_Thickness"
"D1@Regen Slots Sketch" = "Regen_Rib_Thickness"
"D2@Regen Slots Sketch" = "Regen_Thickness"
"D3@Regen Slots Sketch" = "Regen_To_Inner"
"D1@Faceplate Extrusion to Manifold Sketch" = "Faceplate_Area"
"D1@Faceplate Extrusion to Chamber Sketch" = "Faceplate_Area"
"D1@Faceplate Extrusion to Chamber"="Faceplate_To_Chamber_Extrusion"
"D1@O-Ring Slot Sketch" = "Faceplate_Area"
"D2@O-Ring Slot Sketch" = "Injector_MCCN_O-Ring"
"D1@O-Ring Slot" =  ( "Faceplate_To_Chamber_Extrusion" )  +  ( "Injector_MCCN_O-Ring" / 2 ) 
"D1@Fuel Orifices Sketch" = "Ox_Orifice"
"D2@Fuel Orifices Sketch" = "Fuel_Orifice"
"D5@Fuel Orifices Sketch" = "Fuel_Dist_From_Center"
"D3@Fuel Orifices Sketch" = "OxFuel_Dist_Downstream"
"D4@Fuel Orifices Sketch" = "OxFuel_Dist_Downstream"
"D1@Ox1 Profile" = "Ox_Orifice"
"D1@Ox2 Profile" = "Ox_Orifice"
"D1@Ox2 Guide Curve" = "OxFuel_HalfAngle"
"D2@Ox1 Profile" = "OxFuel_Dist_Downstream"
"D2@Ox2 Profile"="OxFuel_Dist_Downstream"
"D1@Ox1 Guide Curve"="OxFuel_HalfAngle"
"Thickness_FuelMan"=5
"D1@Faceplate Extrusion to Manifold"="Thickness_FuelMan"
"OxFuel_Dist_Upstream"= 2* ("OxFuel_Dist_Upstream"= "OxFuel_Dist_Downstream" + ( ( "Thickness_FuelMan" + "Faceplate_To_Chamber_Extrusion") * ( tan ("OxFuel_HalfAngle" ) ) ))
"D4@Ox Profile"="OxFuel_Dist_Upstream"
