"Flange_Dia"= 179.65
"D1@Sketch1"="Flange_Dia"
"Regen_Thickness"= 1.5
"Regen_To_Inner"=2
"Faceplate_Area"=95.65
"Regen_Rib_Thickness"=1
"D2@Sketch1"="Faceplate_Area"
"Flange_Thickness"= 10
"D1@Flange" = "Flange_Thickness"
"D1@Regen Slots Sketch" = "Regen_Rib_Thickness"
"D2@Regen Slots Sketch" = "Regen_Thickness"
"D3@Regen Slots Sketch" = "Regen_To_Inner"
"D1@Faceplate Extrusion to Manifold Sketch" = "Faceplate_Area"
"D1@Faceplate Extrusion to Chamber Sketch" = "Faceplate_Area"
"Faceplate_To_Chamber_Extrusion"=1
"D1@Faceplate Extrusion to Chamber"="Faceplate_To_Chamber_Extrusion"
"D1@O-Ring Slot Sketch" = "Faceplate_Area"
"Injector_MCCN_O-Ring"=3
"D2@O-Ring Slot Sketch" = "Injector_MCCN_O-Ring"
"D1@O-Ring Slot" =  ( "Faceplate_To_Chamber_Extrusion" )  +  ( "Injector_MCCN_O-Ring" / 2 ) 
"Ox_Orifice"= 1.829247371
"D1@Fuel Orifices Sketch" = "Ox_Orifice"
"Fuel_Orifice"= 1.65242067
"D2@Fuel Orifices Sketch" = "Fuel_Orifice"
"OxFuel_Dist_Downstream"= 8
"Fuel_Dist_From_Center"=29.2826
"D1@Ox1 Profile" = "Ox_Orifice"
"D1@Ox2 Profile" = "Ox_Orifice"
"OxFuel_HalfAngle"=30
"D2@Ox1 Profile" = "OxFuel_Dist_Downstream"
"D2@Ox2 Profile"="OxFuel_Dist_Downstream"
"D1@Ox1 Guide Curve"="OxFuel_HalfAngle"
"Thickness_FuelMan"=5
"D1@Faceplate Extrusion to Manifold"="Thickness_FuelMan"
"OxFuel_Dist_Upstream"=((("Thickness_FuelMan" + "Faceplate_To_Chamber_Extrusion")*tan("OxFuel_HalfAngle")))+("OxFuel_Dist_Downstream")
"D7@Fuel Orifices Sketch"=2*"Fuel_Dist_From_Center"
"D3@Fuel Orifices Sketch" = "OxFuel_Dist_Downstream"
"Torch_Igniter_OD"=50.17
"D1@Sketch2"="Torch_Igniter_OD"
